create table if not exists public.market_snapshots (
  id bigint generated by default as identity primary key,
  market_date date not null unique,
  generated_at timestamptz not null,
  score_version text not null,
  market_score numeric(5,2) not null,
  confidence numeric(5,2) not null,
  regime text not null,
  regime_label text not null,
  sp500_price numeric,
  sp500_return_20d numeric,
  nasdaq_price numeric,
  nasdaq_return_20d numeric,
  vix_price numeric,
  usd_jpy_price numeric,
  us10y_yield numeric,
  nikkei225_price numeric,
  nikkei225_return_20d numeric,
  topix_price numeric,
  topix_return_20d numeric,
  indicators jsonb not null default '[]'::jsonb,
  indicator_scores jsonb not null default '[]'::jsonb,
  drivers jsonb not null default '[]'::jsonb,
  warnings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists market_snapshots_market_date_idx
  on public.market_snapshots (market_date desc);

alter table public.market_snapshots enable row level security;

comment on table public.market_snapshots is
  'Daily immutable-style market context used by Strategy Lab and future AI Strategy Advisor.';
