"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Bucket = { label:string; count:number; targetHits:number; targetHitRate:number; averageMfe:number; averageMae:number; averageEndReturn:number; averageHitDay:number|null };
type Payload = { ok:boolean; horizonTradingDays:number; targetReturn:number; snapshotCount:number; scoredSnapshotCount:number; tradeCount:number; latestSnapshotDate:string|null; latestScoredDate:string|null; latestScoredCount:number; overall:Bucket; shortBuy:Bucket; overheated:Bucket; scoreBuckets:Bucket[]; signalBuckets:Bucket[]; categoryBuckets:Bucket[]; regimeBuckets:Bucket[]; etfBuckets:Bucket[]; insights:string[]; methodology:string; error?:string };
const pct=(v:number)=>`${v>0?"+":""}${v.toFixed(2)}%`;
function Card({title,b}:{title:string;b:Bucket}) { return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between gap-3"><h2 className="font-bold">{title}</h2><span className="text-xs text-slate-400">{b.count}件</span></div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><span className="text-slate-500">+2%到達率</span><div className="font-bold text-emerald-300">{b.targetHitRate.toFixed(1)}%</div></div><div><span className="text-slate-500">到達</span><div className="font-bold">{b.targetHits}/{b.count}</div></div><div><span className="text-slate-500">平均MFE</span><div className="font-bold">{pct(b.averageMfe)}</div></div><div><span className="text-slate-500">平均MAE</span><div className="font-bold">{pct(b.averageMae)}</div></div><div><span className="text-slate-500">7日目平均</span><div className="font-bold">{pct(b.averageEndReturn)}</div></div><div><span className="text-slate-500">平均到達日</span><div className="font-bold">{b.averageHitDay===null?"-":`${b.averageHitDay.toFixed(1)}日`}</div></div></div></section> }
function List({title,items}:{title:string;items:Bucket[]}) { return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="mb-3 font-bold">{title}</h2><div className="space-y-2">{items.map(b=><div key={b.label} className="rounded-xl bg-slate-950 p-3"><div className="flex justify-between gap-3"><b>{b.label}</b><span className="text-xs text-slate-400">{b.count}件</span></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs text-slate-300 sm:grid-cols-4"><div>+2% <b className="text-emerald-300">{b.targetHitRate.toFixed(1)}%</b></div><div>MFE <b className="text-white">{pct(b.averageMfe)}</b></div><div>MAE <b className="text-white">{pct(b.averageMae)}</b></div><div>7日目 <b className="text-white">{pct(b.averageEndReturn)}</b></div></div></div>)}</div></section> }
export default function Page(){ const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState(""); useEffect(()=>{fetch("/api/etf-short-learning-summary",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error??"API failed");return j}).then(setData).catch(e=>setError(e instanceof Error?e.message:String(e)))},[]); return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto max-w-6xl p-5 pb-12"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-cyan-300">StockDoc AI Pro</p><h1 className="text-3xl font-bold">ETF Short-Term Learning</h1><p className="mt-1 text-sm text-slate-400">短期Scoreが7営業日以内の+2%を捉えられるか検証</p></div><div className="flex gap-2"><Link href="/etf-learning" className="rounded-xl border border-slate-700 px-3 py-2 text-sm">中期Learning</Link><Link href="/etf" className="rounded-xl border border-slate-700 px-3 py-2 text-sm">← ETF</Link></div></div>{error&&<div className="rounded-xl border border-red-800 bg-red-950 p-4 text-red-200">{error}</div>}{!data&&!error&&<div className="rounded-2xl bg-slate-900 p-5 text-slate-300">短期Learningを集計中...</div>}{data&&<div className="space-y-4"><section className="rounded-2xl border border-cyan-800 bg-cyan-950/30 p-4 text-sm"><div className="flex justify-between gap-3"><b>検証条件</b><b>7営業日 / +2%</b></div><div className="mt-2 grid gap-1 text-slate-300 sm:grid-cols-4"><div>最新Snapshot: {data.latestSnapshotDate??"-"}</div><div>短期Score最新日: {data.latestScoredDate??"-"}</div><div>最新日Score件数: {data.latestScoredCount}</div><div>検証可能: {data.tradeCount}</div></div><p className="mt-3 text-xs text-slate-400">{data.methodology}</p></section>{data.tradeCount===0&&<section className="rounded-2xl border border-amber-800 bg-amber-950/40 p-4 text-sm text-amber-100">短期Score保存開始後の7営業日分がまだそろっていません。Snapshotを毎日蓄積すれば自動的に検証が始まります。</section>}<div className="grid gap-4 md:grid-cols-3"><Card title="全短期Score" b={data.overall}/><Card title="短期BUY" b={data.shortBuy}/><Card title="過熱" b={data.overheated}/></div><section className="rounded-2xl border border-emerald-900 bg-emerald-950/30 p-4"><h2 className="mb-3 font-bold text-emerald-200">Short-Term Learning Insight</h2>{data.insights.map(x=><p key={x} className="mb-2 text-sm text-slate-200">• {x}</p>)}</section><div className="grid gap-4 lg:grid-cols-2"><List title="短期Score帯別" items={data.scoreBuckets}/><List title="短期Signal別" items={data.signalBuckets}/><List title="カテゴリー別" items={data.categoryBuckets}/><List title="Market Regime別" items={data.regimeBuckets}/></div><List title="ETF別成績" items={data.etfBuckets}/></div>}</div></main> }
